spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: dmlwls12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: "94zWvRULIyWxC8qLhiwVoV1Ne2R/C9d5O9+LhCPZUySpGwpiNpxek4FBGZhcXkxpcXfSwwW/h4m8sFJVpXPaEg=="

